### ISSUE TITLE
[BUG/ISSUE] Incompatible with Forgotten Graves

### ISSUE THREAD

**Issue by Answordy** [CerbonXD/BetterTotemOfUndying-FABRIC#2]
When I install this mod and cloth config 8.3.103 into my modpack where several other mods are using cloth config I get this message:
![2023-10-23_22h-53m-48s](https://github.com/CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE/assets/82783515/c6a91d28-8cc7-4e1a-b5ba-ab122347730b)

If I remove or add older cloth config version I get this message:
![2023-10-23_22h-54m-21s](https://github.com/CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE/assets/82783515/63ed51dc-63ea-4543-93f1-8e883e0f2fd8)

If I remove Better Totem of Undying or Forgotten Graves I get no error and the game loads. Not sure which mod is causing the issue.

**Comment by CerbonXD** [comment]
I think that forgotten graves has a version 3.2.2 and you are using 3.2.1. Please try using the 3.2.2 version and see if it works. Looking at his code and also my code, there is nothing wrong.

**Comment by Answordy** [comment]
Yeah, It was a problem with Forgotten Graves, I posted this issue to their tracker too and they fixed it in 3.2.2. Really fast too. So im closing this now.
